apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: three-tier-app
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      # nodePort: 30002
  # type: NodePort