{
 "title": "Euros-Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Frontend Pod CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"frontend.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Pod CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"backend.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"mongo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"grafana\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AlertManager Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"alertmanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Curent Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Free Storage Size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "mongodb_dbstats_freeStorageSize{database=\"euros-vote-db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}