apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-grafana
  namespace: three-tier-app
  labels: 
    app: nginx-grafana
spec:
  selector:
    matchLabels:
      app: nginx-grafana
  template:
    metadata:
      labels:
        app: nginx-grafana
    spec:
      containers:
      - name: nginx-grafana
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-grafana-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-grafana-config
        configMap:
          name: nginx-grafana-config
---
