apiVersion: v1
kind: Service
metadata:
  name: nginx-grafana-lb
  namespace: three-tier-app
  labels:
    app: nginx-grafana
spec:
  selector:
    app: nginx-grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer