---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier-app
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      tolerations:
        # - key: "backend"
        #   operator: "Equal"
        #   value: "true"
        #   effect: "NoSchedule" 
      containers:
        - name: backend
          image: jonathanjhunt/euros-vote-app-backend:latest
          imagePullPolicy: Always
          ports:
            - name:
              containerPort: 3001
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password