---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: three-tier-app
spec:
  selector:
    app: backend
    tier: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    # nodePort: 30001
  # type: NodePort
...