apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: three-tier-app
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer