---
apiVersion: v1
kind: Service
metadata:
  name: frontend-np
  namespace: three-tier-app
spec:
  type: NodePort
  selector:
    app: frontend-np
    tier: frontend-np
  ports:
  - protocol: "TCP"
    port: 30732
    targetPort: 3000
    nodePort: 30732