---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier-app
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      # tolerations:
      #   - key: "frontend"
      #     operator: "Equal"
      #     value: "true"
      #     effect: "NoSchedule"
      containers:
        - name: frontend
          image: jonathanjhunt/euros-vote-app-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "150Mi"
              cpu: "200m"
            limits:
              memory: "250Mi"
              cpu: "200m"

...